version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    restart: always  
    volumes:
      - ./data/db:/data/db
    ports:
      - 7474:7474
      - 7687:7687
    command: neo4j